### ISSUE TITLE
Too many values to unpack

### ISSUE THREAD

**Issue by julian-perge** [RubyTurtwig/dupes-not-included#1]
I keep getting this error after I click run.

```
Traceback (most recent call last):
File "main.py", line 12, in <module>                                                                                      app.gui.run_gui()                                                                                                     

File "C:\Users\Julian\Documents\dupes-not-included-master\app\gui.py", line 21, in run_gui                                s.run(int(number) - 1, filename)                                                                                      

File "C:\Users\Julian\Documents\dupes-not-included-master\app\screen.py", line 439, in run                                self.boxes = self.get_duplicant_box()                                                                                

 File "C:\Users\Julian\Documents\dupes-not-included-master\app\screen.py", line 136, in get_duplicant_box                  image, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)                                                                      ValueError: too many values to unpack (expected 2)
```

Here is my json file that I am using.

`{
    "attributes": {
    },
    "positive": [],
    "negative": [
        "slow learner",
        "noodle arms",
        "loud sleeper",
        "narcoleptic"
    ],
    "interests": [
        "research"
    ]
}`

**Comment by RubyTurtwig** [comment]
Yikes, my first ever issue on github!

Could you try replacing line 135 of screen.py with the code below?
`_, contours, _ = cv2.findContours(`

Thank you!

**Comment by julian-perge** [comment]
> 
> 
> Yikes, my first ever issue on github!
> 
> Could you try replacing line 135 of screen.py with the code below?
> `_, contours, _ = cv2.findContours(`
> 
> Thank you!

Well, now I'm getting this error. I'm using Python 3.4 by the way. What version do you have installed?

```
File "main.py", line 3, in <module>
import app.gui
File "C:\Users\Julian\Documents\dupes-not-included-master\app\gui.py", line 3, in <module>
from .screen import Screen
File "C:\Users\Julian\Documents\dupes-not-included-master\app\screen.py", line 34 
self.shuffle_template = cv2.imread(f'{DIR}shuffle.png', 0)
                                                     ^
SyntaxError: invalid syntax 
```

**Comment by RubyTurtwig** [comment]
I have Python 3.7 installed!

Could you try `pip install opencv-python?`

**Comment by DecoyOtter** [comment]
I'm having similar issue.

`Traceback (most recent call last):
  File "D:\Desktop\dupes-not-included-master\main.py", line 12, in <module>
    app.gui.run_gui()
  File "D:\Desktop\dupes-not-included-master\app\gui.py", line 21, in run_gui
    s.run(int(number) - 1, filename)
  File "D:\Desktop\dupes-not-included-master\app\screen.py", line 439, in run
    self.boxes = self.get_duplicant_box()
  File "D:\Desktop\dupes-not-included-master\app\screen.py", line 136, in get_duplicant_box
    image, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)
ValueError: too many values to unpack (expected 2)`

I have python 3.7, i have also checked that opencv-python was installed and i tried changing line 135 of screen.py as suggested above with no luck.

**Comment by Aurelite** [comment]
in app/screen.py change lines 136 & 169 from 

`contours, _ = cv2.findContours(`
to
`_, contours, _ = cv2.findContours(`

Different versions of OpenCV handle findContours differently, from the [OpenCV Docs](https://docs.opencv.org/3.3.1/d4/d73/tutorial_py_contours_begin.html):

> Since OpenCV 3.2, findContours() no longer modifies the source image but returns a modified image as the first of three return parameters.

**Comment by DecoyOtter** [comment]
Thanks, that seems to have resolved my issue above.

I now see the following error though..

> Traceback (most recent call last):
>   File "D:\Desktop\dupes-not-included-master\main.py", line 12, in <module>
>     app.gui.run_gui()
>   File "D:\Desktop\dupes-not-included-master\app\gui.py", line 21, in run_gui
>     s.run(int(number) - 1, filename)
>   File "D:\Desktop\dupes-not-included-master\app\screen.py", line 439, in run
>     self.boxes = self.get_duplicant_box()
>   File "D:\Desktop\dupes-not-included-master\app\screen.py", line 156, in get_duplicant_box
>     raise NotImplementedError(f'Must find 3 duplicants!')
> NotImplementedError: Must find 3 duplicants!
